//DON'T modify or delete this file. This file is autogenerated and used by deVoid UIFramework
namespace deVoid.UIFramework
{
	public enum ScreenId
	{
		MainMenu,
		SettingsMenu,
		Toast,
		PopupMesage,
		ProfilePanel,
		GameplayUI,
	}
}
